using System;
using System.IO;
using Aspose.Pdf;
using Aspose.Pdf.Facades;

class Program
{
    static void Main()
    {
        const string inputPath  = "input.pdf";
        const string outputPath = "output_with_xmp.pdf";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"Source file not found: {inputPath}");
            return;
        }

        try
        {
            // Load the source PDF
            using (Document doc = new Document(inputPath))
            {
                // Check whether basic document info is present.
                // If none of the common fields are set, we treat the PDF as lacking XMP metadata
                // and inject minimal metadata using the Document.Info object.
                bool hasMetadata = !string.IsNullOrWhiteSpace(doc.Info.Title) ||
                                   !string.IsNullOrWhiteSpace(doc.Info.Author) ||
                                   !string.IsNullOrWhiteSpace(doc.Info.Subject) ||
                                   !string.IsNullOrWhiteSpace(doc.Info.Keywords);

                if (!hasMetadata)
                {
                    // Minimal XMP‑like metadata (Title, Author, Subject, CreationDate)
                    doc.Info.Title       = Path.GetFileNameWithoutExtension(inputPath);
                    doc.Info.Author      = "Generated by Aspose.Pdf";
                    doc.Info.Subject     = "Minimal XMP metadata fallback";
                    doc.Info.Keywords    = "XMP,Fallback,Generated";
                    doc.Info.CreationDate = DateTime.UtcNow;
                }

                // Save the PDF (the Info properties are automatically written into the XMP packet)
                doc.Save(outputPath);
            }

            Console.WriteLine($"PDF saved with fallback metadata to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}