using System;
using System.Data;
using System.IO;
using Aspose.Pdf.Facades;
using Aspose.Pdf;
using NUnit.Framework;

// Minimal NUnit stubs to allow compilation when the NUnit package is not referenced.
namespace NUnit.Framework
{
    [AttributeUsage(AttributeTargets.Class)]
    public sealed class TestFixtureAttribute : Attribute { }

    [AttributeUsage(AttributeTargets.Method)]
    public sealed class TestAttribute : Attribute { }

    public static class Assert
    {
        public static void AreEqual<T>(T expected, T actual, string? message = null)
        {
            if (!object.Equals(expected, actual))
            {
                throw new Exception(message ?? $"Assert.AreEqual failed. Expected:<{expected}>. Actual:<{actual}>.");
            }
        }
    }
}

namespace AsposePdfTests
{
    [TestFixture]
    public class AutoFillerFieldComparisonTests
    {
        // Path to the PDF template that contains form fields with the same names as the DataTable columns.
        private const string TemplatePdfPath = "TemplateForm.pdf";

        // Helper method to create a simple DataTable with one row of test data.
        private static DataTable CreateTestDataTable()
        {
            DataTable table = new DataTable("TestData");
            // Add columns whose names match the form field names in the PDF template.
            table.Columns.Add("FirstName", typeof(string));
            table.Columns.Add("LastName", typeof(string));
            table.Columns.Add("Address", typeof(string));
            table.Columns.Add("City", typeof(string));
            table.Columns.Add("Country", typeof(string));

            // Insert a single row of sample data.
            var row = table.NewRow();
            row["FirstName"] = "John";
            row["LastName"] = "Doe";
            row["Address"] = "123 Main St";
            row["City"] = "Metropolis";
            row["Country"] = "USA";
            table.Rows.Add(row);

            return table;
        }

        [Test]
        public void FilledPdfFields_ShouldMatchOriginalDataTableValues()
        {
            // Arrange
            DataTable sourceTable = CreateTestDataTable();

            // Use a memory stream to hold the filled PDF generated by AutoFiller.
            using (MemoryStream filledPdfStream = new MemoryStream())
            {
                // AutoFiller fills the template PDF with data from the DataTable.
                using (AutoFiller autoFiller = new AutoFiller())
                {
                    // Bind the template PDF file.
                    autoFiller.BindPdf(TemplatePdfPath);

                    // Import the DataTable. This will map each column to a form field of the same name.
                    autoFiller.ImportDataTable(sourceTable);

                    // Save the result into the memory stream (merged output).
                    autoFiller.Save(filledPdfStream);
                }

                // Reset the stream position before reading.
                filledPdfStream.Position = 0;

                // Act
                // Load the filled PDF using the Form facade to read field values.
                using (Form form = new Form(filledPdfStream))
                {
                    // The DataTable contains only one row for this test.
                    DataRow expectedRow = sourceTable.Rows[0];

                    // Iterate through each column/field and compare the value.
                    foreach (DataColumn column in sourceTable.Columns)
                    {
                        string fieldName = column.ColumnName;
                        string expectedValue = expectedRow[fieldName]?.ToString() ?? string.Empty;

                        // Retrieve the actual value from the filled PDF.
                        string actualValue = form.GetField(fieldName) ?? string.Empty;

                        // Assert that the values match.
                        Assert.AreEqual(expectedValue, actualValue,
                            $"Field '{fieldName}' value mismatch. Expected: '{expectedValue}', Actual: '{actualValue}'.");
                    }
                }
            }
        }
    }

    // Dummy entry point to satisfy the compiler when the project is built as an executable.
    public static class Program
    {
        public static void Main() { }
    }
}
