using System;
using System.IO;
using Aspose.Pdf;
using Aspose.Pdf.Tagged;
using Aspose.Pdf.LogicalStructure;
using Aspose.Pdf.Text; // for TextFragment and FontStyles

class Program
{
    static void Main()
    {
        const string inputPath  = "input.pdf";
        const string outputPath = "output_with_toc.pdf";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        // Load the source PDF inside a using block for deterministic disposal
        using (Document doc = new Document(inputPath))
        {
            // Access the tagged content interface and set basic metadata
            ITaggedContent tagged = doc.TaggedContent;
            tagged.SetLanguage("en-US");
            tagged.SetTitle(Path.GetFileNameWithoutExtension(inputPath));

            // Insert a new page at the beginning to hold the Table of Contents
            Page tocPage = doc.Pages.Insert(1);

            // Add a visual title on the TOC page
            TextFragment tocTitle = new TextFragment("Table of Contents");
            tocTitle.TextState.FontSize = 20;
            tocTitle.TextState.FontStyle = FontStyles.Bold;
            tocPage.Paragraphs.Add(tocTitle);

            // Build the logical structure for the TOC page
            StructureElement root = tagged.RootElement; // no cast needed

            // Create a heading element for the TOC title and attach it to the root
            HeaderElement tocHeader = tagged.CreateHeaderElement(1);
            tocHeader.SetText("Table of Contents");
            root.AppendChild(tocHeader);

            // Add heading entries as paragraph elements.
            // In a real scenario these would be generated by scanning the document.
            ParagraphElement entry1 = tagged.CreateParagraphElement();
            entry1.SetText("1. Introduction ........................................ 2");
            root.AppendChild(entry1);

            ParagraphElement entry2 = tagged.CreateParagraphElement();
            entry2.SetText("2. Conclusion ........................................ 10");
            root.AppendChild(entry2);

            // Save the modified PDF; no PreSave call is required
            doc.Save(outputPath);
        }

        Console.WriteLine($"PDF with Table of Contents saved to '{outputPath}'.");
    }
}