using System;
using System.Collections.Generic;
using System.IO;
using System.Xml.Linq;

namespace PdfValidationReportSummary
{
    class Program
    {
        static void Main()
        {
            // Path to the XML validation report generated by Aspose.Pdf.Document.Validate(...)
            const string reportPath = "validation_report.xml";

            if (!File.Exists(reportPath))
            {
                Console.Error.WriteLine($"Report file not found: {reportPath}");
                return;
            }

            try
            {
                // Load the XML document
                XDocument doc = XDocument.Load(reportPath);

                // Dictionaries to hold counts per error code and per message
                var codeCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
                var messageCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);

                // The expected XML structure (based on Aspose.Pdf validation output) is:
                // <ValidationReport>
                //   <Error>
                //     <Code>...</Code>
                //     <Message>...</Message>
                //   </Error>
                //   ...
                // </ValidationReport>
                foreach (var errorElement in doc.Descendants("Error"))
                {
                    // Extract code and message; if missing, use placeholders
                    string code = (string)errorElement.Element("Code") ?? "UNKNOWN_CODE";
                    string message = (string)errorElement.Element("Message") ?? "No message";

                    // Increment code count
                    if (codeCounts.ContainsKey(code))
                        codeCounts[code]++;
                    else
                        codeCounts[code] = 1;

                    // Increment message count
                    if (messageCounts.ContainsKey(message))
                        messageCounts[message]++;
                    else
                        messageCounts[message] = 1;
                }

                // Output summary of error codes
                Console.WriteLine("=== Error Code Summary ===");
                foreach (var kvp in codeCounts)
                {
                    Console.WriteLine($"Code: {kvp.Key}  Count: {kvp.Value}");
                }

                // Output most common messages (top 5)
                Console.WriteLine();
                Console.WriteLine("=== Common Error Messages (Top 5) ===");
                foreach (var kvp in GetTopN(messageCounts, 5))
                {
                    Console.WriteLine($"Message: \"{kvp.Key}\"  Count: {kvp.Value}");
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Failed to process report: {ex.Message}");
            }
        }

        // Helper to retrieve the top N entries from a dictionary sorted by descending count
        private static IEnumerable<KeyValuePair<string, int>> GetTopN(Dictionary<string, int> dict, int n)
        {
            var list = new List<KeyValuePair<string, int>>(dict);
            list.Sort((a, b) => b.Value.CompareTo(a.Value)); // descending
            for (int i = 0; i < Math.Min(n, list.Count); i++)
                yield return list[i];
        }
    }
}