using System;
using System.IO;
using Aspose.Pdf;
using Aspose.Pdf.Annotations;
using Aspose.Pdf.Text; // Added for TextFragment

class Program
{
    static void Main()
    {
        // Paths for the source PDF, target PDF, intermediate XFDF file, and final output PDF
        const string sourcePdfPath = "source.pdf";
        const string targetPdfPath = "target.pdf";
        const string xfdfPath = "annotations.xfdf";
        const string outputPdfPath = "target_with_annotations.pdf";

        // ------------------------------------------------------------
        // Ensure sample PDFs exist (create them if they are missing)
        // ------------------------------------------------------------
        if (!File.Exists(sourcePdfPath))
            CreateSamplePdf(sourcePdfPath, withAnnotations: true);
        if (!File.Exists(targetPdfPath))
            CreateSamplePdf(targetPdfPath, withAnnotations: false);

        // ------------------------------------------------------------
        // Export all annotations from the source PDF to an XFDF file
        // ------------------------------------------------------------
        using (Document sourceDoc = new Document(sourcePdfPath))
        {
            // The ExportAnnotationsToXfdf method writes the XFDF data to the specified file
            sourceDoc.ExportAnnotationsToXfdf(xfdfPath);
        }

        // ------------------------------------------------------------
        // Import the previously exported XFDF into the target PDF
        // ------------------------------------------------------------
        using (Document targetDoc = new Document(targetPdfPath))
        {
            // The ImportAnnotationsFromXfdf method reads the XFDF file and adds the annotations to the document
            targetDoc.ImportAnnotationsFromXfdf(xfdfPath);

            // Save the modified target PDF with the imported annotations
            targetDoc.Save(outputPdfPath);
        }

        Console.WriteLine("Annotations exported from source PDF and imported into target PDF successfully.");
    }

    /// <summary>
    /// Creates a simple PDF file. If <paramref name="withAnnotations"/> is true, a sample text annotation is added.
    /// </summary>
    private static void CreateSamplePdf(string path, bool withAnnotations)
    {
        using (Document doc = new Document())
        {
            // Add a single blank page
            Page page = doc.Pages.Add();
            page.Paragraphs.Add(new TextFragment("Sample PDF generated by the demo program."));

            if (withAnnotations)
            {
                // Add a simple text annotation to demonstrate export/import
                TextAnnotation txtAnn = new TextAnnotation(page, new Aspose.Pdf.Rectangle(100, 600, 300, 650))
                {
                    Title = "Demo Annotation",
                    Subject = "Export/Import Test",
                    Contents = "This annotation will be exported to XFDF and imported into another PDF."
                };
                page.Annotations.Add(txtAnn);
            }

            doc.Save(path);
        }
    }
}
