using System;
using System.IO;
using Aspose.Pdf;
using Aspose.Pdf.Drawing;

class Program
{
    static void Main()
    {
        // Create a new PDF document inside a using block for proper disposal
        using (Document pdfDoc = new Document())
        {
            // Add a blank page to the document
            Page page = pdfDoc.Pages.Add();

            // Create a Graph container (width: 400 points, height: 200 points)
            Graph graph = new Graph(400, 200);

            // Draw X‑axis
            float[] xAxisPoints = { 50, 150, 350, 150 };
            Line xAxis = new Line(xAxisPoints);
            xAxis.GraphInfo = new GraphInfo
            {
                Color = Color.Black,
                LineWidth = 1
            };
            graph.Shapes.Add(xAxis);

            // Draw Y‑axis
            float[] yAxisPoints = { 50, 150, 50, 50 };
            Line yAxis = new Line(yAxisPoints);
            yAxis.GraphInfo = new GraphInfo
            {
                Color = Color.Black,
                LineWidth = 1
            };
            graph.Shapes.Add(yAxis);

            // Draw a simple line graph representing sample data
            // Points: (50,150) → (100,120) → (150,130) → (200,90) → (250,110) → (300,80)
            float[] dataPoints = { 50, 150, 100, 120, 150, 130, 200, 90, 250, 110, 300, 80 };
            Line dataLine = new Line(dataPoints);
            dataLine.GraphInfo = new GraphInfo
            {
                Color = Color.Blue,
                LineWidth = 2
            };
            graph.Shapes.Add(dataLine);

            // Add the graph to the page's paragraph collection
            page.Paragraphs.Add(graph);

            // Serialize the PDF document to a memory stream and obtain the byte array
            using (MemoryStream ms = new MemoryStream())
            {
                pdfDoc.Save(ms);               // Save PDF content into the stream
                byte[] pdfBytes = ms.ToArray(); // Convert stream to byte array

                // Example usage: output the size of the generated byte array
                Console.WriteLine($"Generated PDF byte array length: {pdfBytes.Length}");
                // The byte array (pdfBytes) can now be transmitted over a network
            }
        }
    }
}