using System;
using System.IO;
using System.IO.Compression;
using Aspose.Pdf;
using Aspose.Pdf.Comparison;
using Aspose.Pdf.Devices;

class Program
{
    static void Main()
    {
        const string pdfPath1 = "original.pdf";
        const string pdfPath2 = "modified.pdf";
        const string zipOutputPath = "diff_images.zip";

        // Verify input files exist
        if (!File.Exists(pdfPath1) || !File.Exists(pdfPath2))
        {
            Console.Error.WriteLine("One or both input PDF files were not found.");
            return;
        }

        // Create a temporary folder to store diff images (and an intermediate comparison PDF)
        string tempDiffFolder = Path.Combine(Path.GetTempPath(), "PdfDiff_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDiffFolder);

        // Path for the visual side‑by‑side comparison PDF generated by Aspose
        string tempComparisonPdf = Path.Combine(tempDiffFolder, "comparison.pdf");

        try
        {
            // Load the source PDFs
            Document doc1 = new Document(pdfPath1);
            Document doc2 = new Document(pdfPath2);

            // Perform side‑by‑side visual comparison – the method is static and writes a PDF
            SideBySidePdfComparer.Compare(doc1, doc2, tempComparisonPdf, new SideBySideComparisonOptions());

            // Convert each page of the comparison PDF to PNG images
            Document comparisonDoc = new Document(tempComparisonPdf);
            int pageNumber = 1;
            foreach (Page page in comparisonDoc.Pages)
            {
                string imagePath = Path.Combine(tempDiffFolder, $"page_{pageNumber}.png");
                // Use PngDevice (high‑resolution PNG) for conversion
                var pngDevice = new PngDevice(new Resolution(150));
                pngDevice.Process(page, imagePath);
                pageNumber++;
            }

            // Package all generated images into a zip archive for easy distribution
            ZipFile.CreateFromDirectory(tempDiffFolder, zipOutputPath);
            Console.WriteLine($"Diff images have been zipped to '{zipOutputPath}'.");
        }
        finally
        {
            // Clean up the temporary folder (including the intermediate PDF)
            if (Directory.Exists(tempDiffFolder))
            {
                try { Directory.Delete(tempDiffFolder, true); } catch { /* ignore cleanup errors */ }
            }
        }
    }
}
