using System;
using System.IO;
using Aspose.Pdf;

class Program
{
    static void Main()
    {
        // Define the directory where crash reports will be saved
        string crashReportDir = Path.Combine(Environment.CurrentDirectory, "CrashReports");
        Directory.CreateDirectory(crashReportDir); // Ensure the directory exists

        try
        {
            // Simulate an exception to generate a crash report
            int zero = 0;
            int result = 10 / zero; // This will throw DivideByZeroException
        }
        catch (Exception ex)
        {
            // Create CrashReportOptions based on the caught exception and configure output
            var options = new CrashReportOptions(ex)
            {
                CrashReportDirectory = crashReportDir,
                CrashReportFilename = "crash_report.html",
                CustomMessage = "Demo crash report generated by sample code."
            };

            // Generate the crash report HTML file
            PdfException.GenerateCrashReport(options);

            // Verify that the report file was created successfully
            string reportPath = Path.Combine(crashReportDir, options.CrashReportFilename);
            if (File.Exists(reportPath))
            {
                Console.WriteLine($"Crash report saved at: {reportPath}");
            }
            else
            {
                Console.WriteLine("Crash report generation failed.");
            }
        }
    }
}
