using System;
using System.Collections.Generic;
using Aspose.Pdf;
using Aspose.Pdf.Text;

class Program
{
    // Helper to convert integer to uppercase Roman numerals (I, II, III, …)
    static string ToRoman(int number)
    {
        if (number < 1) return string.Empty;
        var map = new[] {
            new { Value = 1000, Numeral = "M" },
            new { Value = 900,  Numeral = "CM" },
            new { Value = 500,  Numeral = "D" },
            new { Value = 400,  Numeral = "CD" },
            new { Value = 100,  Numeral = "C" },
            new { Value = 90,   Numeral = "XC" },
            new { Value = 50,   Numeral = "L" },
            new { Value = 40,   Numeral = "XL" },
            new { Value = 10,   Numeral = "X" },
            new { Value = 9,    Numeral = "IX" },
            new { Value = 5,    Numeral = "V" },
            new { Value = 4,    Numeral = "IV" },
            new { Value = 1,    Numeral = "I" }
        };

        var result = string.Empty;
        foreach (var entry in map)
        {
            while (number >= entry.Value)
            {
                result += entry.Numeral;
                number -= entry.Value;
            }
        }
        return result;
    }

    static void Main()
    {
        const string outputPath = "RomanHeadings.pdf";
        const int headingCount = 5; // number of headings to create

        // -------------------------------------------------
        // Create a PDF with headings that use Roman numerals
        // -------------------------------------------------
        using (Document doc = new Document())
        {
            // Add a single page (headings will be placed sequentially on this page)
            Page page = doc.Pages.Add();

            for (int i = 1; i <= headingCount; i++)
            {
                // Create a heading of level 1
                Heading heading = new Heading(1)
                {
                    // Enable automatic sequencing and list numbering
                    IsInList = true,
                    IsAutoSequence = true,
                    // Use uppercase Roman numerals for the list style
                    Style = NumberingStyle.NumeralsRomanUppercase,
                    // The actual text of the heading (the number will be prefixed automatically)
                    Text = $"Section {i}",
                    // Optional margin for visual spacing
                    Margin = new MarginInfo(20, 20, 20, 20)
                };

                // Add the heading to the page
                page.Paragraphs.Add(heading);
            }

            // Save the document
            doc.Save(outputPath);
        }

        // -------------------------------------------------
        // Validate that the headings are numbered with Roman numerals in correct order
        // -------------------------------------------------
        using (Document loadedDoc = new Document(outputPath))
        {
            // Collect heading texts from the first page
            List<string> headingTexts = new List<string>();
            foreach (var paragraph in loadedDoc.Pages[1].Paragraphs)
            {
                if (paragraph is Heading h)
                {
                    headingTexts.Add(h.Text);
                }
            }

            // Expected Roman numerals for the sequence 1..headingCount
            List<string> expectedRomans = new List<string>();
            for (int i = 1; i <= headingCount; i++)
                expectedRomans.Add(ToRoman(i));

            // Verify each heading starts with the expected Roman numeral
            bool sequenceIsCorrect = true;
            for (int i = 0; i < headingTexts.Count && i < expectedRomans.Count; i++)
            {
                string heading = headingTexts[i];
                string expectedRoman = expectedRomans[i];

                // The heading text generated by Aspose.Pdf places the number before the user text,
                // separated by a space (e.g., "I Section 1")
                if (!heading.StartsWith(expectedRoman + " "))
                {
                    sequenceIsCorrect = false;
                    Console.WriteLine($"Mismatch at heading {i + 1}: expected prefix '{expectedRoman}', found '{heading}'.");
                }
            }

            if (sequenceIsCorrect && headingTexts.Count == headingCount)
                Console.WriteLine("Roman numeral heading sequence is correct.");
            else
                Console.WriteLine("Roman numeral heading sequence validation failed.");
        }
    }
}