using System;
using System.IO;
using Aspose.Pdf;
using Aspose.Pdf.Text; // required for HtmlSaveOptions (inherits from UnifiedSaveOptions)
 
class PdfToResponsiveHtml
{
    static void Main()
    {
        // Input PDF path
        const string pdfPath = "input.pdf";
        // Temporary HTML output path (generated by Aspose.Pdf)
        const string htmlPath = "output.html";
        // Path to the responsive CSS file you want to apply
        const string cssPath = "responsive.css";
 
        if (!File.Exists(pdfPath))
        {
            Console.Error.WriteLine($"PDF file not found: {pdfPath}");
            return;
        }
        if (!File.Exists(cssPath))
        {
            Console.Error.WriteLine($"CSS file not found: {cssPath}");
            return;
        }
 
        try
        {
            // Load the PDF document
            using (Document pdfDoc = new Document(pdfPath))
            {
                // Configure HTML conversion options
                HtmlSaveOptions htmlOpts = new HtmlSaveOptions
                {
                    // Generate a single HTML file (all pages merged)
                    SplitIntoPages = false,
                    // Use flow layout for better responsiveness
                    FixedLayout = false,
                    // Embed images as PNG inside SVG to keep a single file
                    RasterImagesSavingMode = HtmlSaveOptions.RasterImagesSavingModes.AsPngImagesEmbeddedIntoSvg,
                    // Optional: embed CSS into the HTML (we will replace it later)
                    // Title can be set if desired
                    Title = Path.GetFileNameWithoutExtension(pdfPath)
                };
 
                // Save PDF as HTML
                pdfDoc.Save(htmlPath, htmlOpts);
            }
 
            // Read the generated HTML
            string htmlContent = File.ReadAllText(htmlPath);
 
            // Prepare the CSS link tag (relative path)
            string cssLinkTag = $"<link rel=\"stylesheet\" type=\"text/css\" href=\"{Path.GetFileName(cssPath)}\" />";
 
            // Insert a viewport meta tag and the CSS link into the <head> section
            // Ensure we have a <head> element; if not, create a simple one.
            if (!htmlContent.Contains("<head>", StringComparison.OrdinalIgnoreCase))
            {
                // Insert a basic <head> before the first <body>
                int bodyIdx = htmlContent.IndexOf("<body", StringComparison.OrdinalIgnoreCase);
                if (bodyIdx >= 0)
                {
                    string headSection = "<head>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                                         + cssLinkTag + "\n</head>\n";
                    htmlContent = htmlContent.Insert(bodyIdx, headSection);
                }
            }
            else
            {
                // Insert after the opening <head> tag
                int headCloseIdx = htmlContent.IndexOf("<head>", StringComparison.OrdinalIgnoreCase) + "<head>".Length;
                string insertion = "\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                                   + cssLinkTag + "\n";
                htmlContent = htmlContent.Insert(headCloseIdx, insertion);
            }
 
            // Write the modified HTML back to the same file
            File.WriteAllText(htmlPath, htmlContent);
 
            Console.WriteLine($"PDF successfully converted to responsive HTML: {htmlPath}");
        }
        catch (TypeInitializationException)
        {
            // HTML conversion relies on GDI+ and is Windows‑only
            Console.Error.WriteLine("HTML conversion requires Windows (GDI+). Operation skipped on this platform.");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error during conversion: {ex.Message}");
        }
    }
}