using System;
using System.IO;
using System.IO.Compression;
using Aspose.Pdf;

class Program
{
    static void Main()
    {
        const string inputPdfPath = "input.pdf";
        const string zipOutputPath = "pdf_html_archive.zip";

        if (!File.Exists(inputPdfPath))
        {
            Console.Error.WriteLine($"Input PDF not found: {inputPdfPath}");
            return;
        }

        // Create a temporary folder to hold the HTML pages and assets generated by Aspose.Pdf
        string tempFolder = Path.Combine(Path.GetTempPath(), "PdfToHtml_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempFolder);

        // Base name for the first HTML file; Aspose.Pdf will create additional files (page_2.html, assets folder, etc.)
        string htmlBasePath = Path.Combine(tempFolder, "output.html");

        // Load the PDF and convert to HTML (one HTML file per page)
        using (Document pdfDoc = new Document(inputPdfPath))
        {
            HtmlSaveOptions htmlOpts = new HtmlSaveOptions
            {
                SplitIntoPages = true,
                RasterImagesSavingMode = HtmlSaveOptions.RasterImagesSavingModes.AsPngImagesEmbeddedIntoSvg
            };

            try
            {
                pdfDoc.Save(htmlBasePath, htmlOpts);
                Console.WriteLine("PDF successfully converted to HTML.");
            }
            catch (TypeInitializationException)
            {
                // HTML conversion requires GDI+ and is Windows‑only
                Console.WriteLine("HTML conversion requires Windows (GDI+). Operation skipped.");
                CleanupTempFolder(tempFolder);
                return;
            }
        }

        // Create a ZIP archive containing all generated HTML files and assets
        using (ZipArchive zip = ZipFile.Open(zipOutputPath, ZipArchiveMode.Create))
        {
            foreach (string filePath in Directory.GetFiles(tempFolder, "*", SearchOption.AllDirectories))
            {
                // Preserve folder structure inside the ZIP
                string entryName = Path.GetRelativePath(tempFolder, filePath);
                zip.CreateEntryFromFile(filePath, entryName);
            }
        }

        Console.WriteLine($"HTML pages and assets zipped to: {zipOutputPath}");

        // Optional: clean up temporary files
        CleanupTempFolder(tempFolder);
    }

    static void CleanupTempFolder(string folderPath)
    {
        try
        {
            if (Directory.Exists(folderPath))
                Directory.Delete(folderPath, true);
        }
        catch
        {
            // Suppress any cleanup errors
        }
    }
}