using System;
using System.IO;
using Aspose.Pdf;

class Program
{
    static void Main()
    {
        // Paths – adjust as needed
        const string inputPdfPath   = "input.pdf";
        const string outputHtmlPath = "output.html";

        // Simple responsive CSS – you can replace this with a link to an external stylesheet
        const string responsiveCss = @"
<style>
/* Mobile‑friendly responsive layout */
html, body { margin:0; padding:0; width:100%; height:auto; }
img { max-width:100%; height:auto; }
@media only screen and (max-width:600px) {
    .stl_01, .stl_02, .stl_03 { /* example class prefixes generated by Aspose */
        width:100% !important;
        display:block !important;
    }
}
</style>";

        if (!File.Exists(inputPdfPath))
        {
            Console.Error.WriteLine($"Input PDF not found: {inputPdfPath}");
            return;
        }

        try
        {
            // Load the PDF document (lifecycle rule: using block)
            using (Document pdfDoc = new Document(inputPdfPath))
            {
                // Configure HTML conversion options (must pass explicit SaveOptions)
                HtmlSaveOptions htmlOpts = new HtmlSaveOptions
                {
                    // Example: embed raster images as PNG inside SVG wrappers
                    RasterImagesSavingMode = HtmlSaveOptions.RasterImagesSavingModes.AsPngImagesEmbeddedIntoSvg,
                    // Optional: generate a single HTML file (no page splitting)
                    SplitIntoPages = false
                };

                // Save as HTML – explicit HtmlSaveOptions required (otherwise PDF is written)
                pdfDoc.Save(outputHtmlPath, htmlOpts);
            }

            // At this point the HTML file exists. Inject responsive CSS.
            string htmlContent = File.ReadAllText(outputHtmlPath);

            // Insert the CSS just after the opening <head> tag.
            const string headTag = "<head>";
            int headPos = htmlContent.IndexOf(headTag, StringComparison.OrdinalIgnoreCase);
            if (headPos >= 0)
            {
                int insertPos = headPos + headTag.Length;
                htmlContent = htmlContent.Insert(insertPos, responsiveCss);
            }
            else
            {
                // Fallback: prepend CSS at the very beginning
                htmlContent = responsiveCss + htmlContent;
            }

            // Overwrite the HTML file with the modified content
            File.WriteAllText(outputHtmlPath, htmlContent);

            Console.WriteLine($"PDF successfully converted to responsive HTML: {outputHtmlPath}");
        }
        catch (TypeInitializationException)
        {
            // HTML conversion relies on GDI+ and is Windows‑only.
            Console.WriteLine("HTML conversion requires Windows (GDI+). Operation skipped on this platform.");
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error during conversion: {ex.Message}");
        }
    }
}