using System;
using System.IO;
using System.IO.Compression;
using Aspose.Pdf;

class Program
{
    static void Main()
    {
        const string pdfPath = "input.pdf";
        const string outputFolder = "html_output";
        const string zipPath = "pdf_html_archive.zip";

        if (!File.Exists(pdfPath))
        {
            Console.Error.WriteLine($"PDF file not found: {pdfPath}");
            return;
        }

        Directory.CreateDirectory(outputFolder);

        string htmlFile = Path.Combine(outputFolder, "document.html");

        using (Document pdfDoc = new Document(pdfPath))
        {
            HtmlSaveOptions htmlOpts = new HtmlSaveOptions
            {
                SplitIntoPages = true,
                // Use NoEmbedding to keep images, CSS, etc. as external files (replaces removed SaveExternalResources)
                PartsEmbeddingMode = HtmlSaveOptions.PartsEmbeddingModes.NoEmbedding
            };
            pdfDoc.Save(htmlFile, htmlOpts);
        }

        // Create ZIP archive containing the HTML file and its resource folder
        if (File.Exists(zipPath))
            File.Delete(zipPath);

        using (FileStream zipStream = new FileStream(zipPath, FileMode.Create))
        using (ZipArchive archive = new ZipArchive(zipStream, ZipArchiveMode.Create))
        {
            // Add the main HTML file
            archive.CreateEntryFromFile(htmlFile, Path.GetFileName(htmlFile));

            // Add all external resource files generated by the HTML conversion
            string resourcesFolder = Path.Combine(outputFolder, Path.GetFileNameWithoutExtension(htmlFile) + "_files");
            if (Directory.Exists(resourcesFolder))
            {
                foreach (string filePath in Directory.GetFiles(resourcesFolder, "*", SearchOption.AllDirectories))
                {
                    string entryName = Path.GetRelativePath(outputFolder, filePath).Replace('\\', '/');
                    archive.CreateEntryFromFile(filePath, entryName);
                }
            }
        }

        Console.WriteLine($"HTML conversion and ZIP archive created at '{zipPath}'.");
    }
}
