using System;
using System.IO;
using System.Threading;
using Aspose.Pdf;
using Aspose.Pdf.Text; // Added for TextFragment and Position

class PdfGenerator
{
    // Generates a PDF from an existing PDF file with retry logic for transient I/O errors.
    // Returns true if the PDF was generated successfully, false otherwise.
    public static bool GeneratePdfWithRetry(string inputPath, string outputPath, int maxRetries = 3, int delayMilliseconds = 500)
    {
        if (string.IsNullOrEmpty(inputPath))
            throw new ArgumentException("Input path must be provided.", nameof(inputPath));
        if (string.IsNullOrEmpty(outputPath))
            throw new ArgumentException("Output path must be provided.", nameof(outputPath));

        int attempt = 0;
        while (true)
        {
            try
            {
                // Load the source PDF document.
                using (Document doc = new Document(inputPath))
                {
                    // Example processing: add a simple text fragment to the first page.
                    // This demonstrates that some work can be done before saving.
                    if (doc.Pages.Count > 0)
                    {
                        var page = doc.Pages[1]; // 1‑based indexing
                        TextFragment text = new TextFragment("Generated by PdfGenerator");
                        text.Position = new Position(100, 700);
                        page.Paragraphs.Add(text);
                    }

                    // Save the resulting PDF.
                    doc.Save(outputPath);
                }

                // If we reach this point, the operation succeeded.
                return true;
            }
            catch (PdfException) // Transient PDF‑related I/O error.
            {
                attempt++;
                if (attempt > maxRetries)
                    return false; // Exhausted retries.

                // Wait before retrying (simple exponential back‑off).
                Thread.Sleep(delayMilliseconds * attempt);
            }
            catch (IOException) // General I/O error (e.g., file lock).
            {
                attempt++;
                if (attempt > maxRetries)
                    return false; // Exhausted retries.

                Thread.Sleep(delayMilliseconds * attempt);
            }
        }
    }

    // Example usage.
    static void Main()
    {
        const string inputPdf = "input.pdf";
        const string outputPdf = "output_generated.pdf";

        if (!File.Exists(inputPdf))
        {
            Console.Error.WriteLine($"Input file not found: {inputPdf}");
            return;
        }

        bool success = GeneratePdfWithRetry(inputPdf, outputPdf);
        Console.WriteLine(success
            ? $"PDF generated successfully: {outputPdf}"
            : "Failed to generate PDF after retries.");
    }
}
