// AsposePdfApi.GlobalUsings.g.cs
// <auto-generated>
// This file provides the global using directives required by the project.
// It resolves the CS2001 error caused by the missing generated file.

global using System;
global using System.IO;
global using Aspose.Pdf;
global using Aspose.Pdf.Facades;
global using Aspose.Pdf.Drawing;
global using Aspose.Pdf.Text;

// ------------------------------------------------------------
// Program.cs
// ------------------------------------------------------------

class Program
{
    static void Main()
    {
        const string inputPdf = "form.pdf";
        const string outputPdf = "form_report.pdf";

        if (!File.Exists(inputPdf))
        {
            Console.Error.WriteLine($"Input file not found: {inputPdf}");
            return;
        }

        // Load the source PDF (no need for FormEditor just to read fields)
        using (Document srcDoc = new Document(inputPdf))
        {
            // Create a new PDF document for the report
            using (Document reportDoc = new Document())
            {
                // Add a page to the report document
                Page page = reportDoc.Pages.Add();

                // Create a table with three columns: Name, Type, Value
                Table table = new Table
                {
                    ColumnWidths = "150 100 200",
                    Border = new BorderInfo(BorderSide.All, 0.5f, Aspose.Pdf.Color.Black)
                };

                // Header row
                Row header = table.Rows.Add();
                header.Cells.Add("Field Name");
                header.Cells.Add("Field Type");
                header.Cells.Add("Field Value");

                // Style the header cells
                foreach (Cell cell in header.Cells)
                {
                    cell.BackgroundColor = Aspose.Pdf.Color.LightGray;
                    cell.DefaultCellTextState = new TextState
                    {
                        FontSize = 12,
                        FontStyle = FontStyles.Bold
                    };
                }

                // Populate the table with field data
                foreach (var field in srcDoc.Form.Fields)
                {
                    string name = field.FullName; // full field name
                    string type = field.GetType().Name; // e.g., TextBoxField, CheckBoxField, etc.
                    string value = field.Value != null ? field.Value.ToString() : string.Empty;

                    Row row = table.Rows.Add();
                    row.Cells.Add(name);
                    row.Cells.Add(type);
                    row.Cells.Add(value);
                }

                // Add the table to the page
                page.Paragraphs.Add(table);

                // Save the report PDF
                reportDoc.Save(outputPdf);
            }
        }

        Console.WriteLine($"Form fields report saved to '{outputPdf}'.");
    }
}
